wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.32
    framework: huggingface
    huggingface_version: 4.3.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      1:
      - 1
      - 3
      - 5
      - 11
      4: 3.7.10
      5: 0.10.32
      6: 4.3.2
      8:
      - 5
batch_size:
  desc: null
  value: 64
batch_size_classifier:
  desc: null
  value: 32
classifier_model:
  desc: null
  value: bert-base-uncased
dataset:
  desc: null
  value: twitter_dataset
learning_rate:
  desc: null
  value: 0.000141
num_epochs:
  desc: null
  value: 15
num_epochs_classifier:
  desc: null
  value: 3
